inherit_from: "https://raw.githubusercontent.com/brandonweiss/rubocop-config/e4d46868424c13e59ea3c8be98074d29dd598d15/default.yml"

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/*"
    - "exe/*"
    - "vendor/**/*"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "test/**/*"

Style/FileName:
  Exclude:
    - "lib/git-hookshot.rb"
